set(EDGE_AGENT_PROJECT_LOG_PREFIX "[edge_agent]")
set(EDGE_AGENT_FLASH_SIZE "")
set(EDGE_AGENT_BOARD_MANAGER_DEFAULTS "${CMAKE_SOURCE_DIR}/components/gen_bmgr_codes/board_manager.defaults")
set(EDGE_AGENT_SDKCONFIG_DEFAULTS "")

if(SDKCONFIG_DEFAULTS)
    set(EDGE_AGENT_SDKCONFIG_DEFAULTS "${SDKCONFIG_DEFAULTS}")
elseif(NOT "$ENV{SDKCONFIG_DEFAULTS}" STREQUAL "")
    set(EDGE_AGENT_SDKCONFIG_DEFAULTS "$ENV{SDKCONFIG_DEFAULTS}")
else()
    set(EDGE_AGENT_SDKCONFIG_DEFAULTS "${CMAKE_SOURCE_DIR}/sdkconfig.defaults")
endif()

if(EXISTS "${EDGE_AGENT_BOARD_MANAGER_DEFAULTS}")
    list(APPEND EDGE_AGENT_SDKCONFIG_DEFAULTS "${EDGE_AGENT_BOARD_MANAGER_DEFAULTS}")

    if(EXISTS "${CMAKE_SOURCE_DIR}/sdkconfig")
        file(READ "${CMAKE_SOURCE_DIR}/sdkconfig" EDGE_AGENT_SDKCONFIG_CONTENT)
        set(EDGE_AGENT_SDKCONFIG_ORIGINAL_CONTENT "${EDGE_AGENT_SDKCONFIG_CONTENT}")
        string(REGEX REPLACE "(^|\n)(# )?CONFIG_ESP_BOARD_[A-Za-z0-9_]+[^\n]*\n" "\\1" EDGE_AGENT_SDKCONFIG_CONTENT "${EDGE_AGENT_SDKCONFIG_CONTENT}")

        if(NOT EDGE_AGENT_SDKCONFIG_CONTENT STREQUAL EDGE_AGENT_SDKCONFIG_ORIGINAL_CONTENT)
            file(WRITE "${CMAKE_SOURCE_DIR}/sdkconfig" "${EDGE_AGENT_SDKCONFIG_CONTENT}")
            message(STATUS "${EDGE_AGENT_PROJECT_LOG_PREFIX} Removed stale board-manager options from sdkconfig")
        endif()
    endif()

    file(STRINGS "${EDGE_AGENT_BOARD_MANAGER_DEFAULTS}" _flash_line REGEX "^CONFIG_ESPTOOLPY_FLASHSIZE_(4|8|16|32)MB=y$")
    if(_flash_line)
        list(GET _flash_line 0 _flash_line)
        string(REGEX REPLACE "^CONFIG_ESPTOOLPY_FLASHSIZE_((4|8|16|32)MB)=y$" "\\1" EDGE_AGENT_FLASH_SIZE "${_flash_line}")
    endif()
endif()

if(EDGE_AGENT_FLASH_SIZE)
    if(EXISTS "${CMAKE_SOURCE_DIR}/sdkconfig")
        file(READ "${CMAKE_SOURCE_DIR}/sdkconfig" EDGE_AGENT_SDKCONFIG_CONTENT)
        string(REGEX REPLACE "(^|\\n)CONFIG_PARTITION_TABLE_CUSTOM_FILENAME=\"[^\\n]*\"\\n" "\\1" EDGE_AGENT_SDKCONFIG_CONTENT "${EDGE_AGENT_SDKCONFIG_CONTENT}")
        string(REGEX REPLACE "(^|\\n)CONFIG_PARTITION_TABLE_FILENAME=\"[^\\n]*\"\\n" "\\1" EDGE_AGENT_SDKCONFIG_CONTENT "${EDGE_AGENT_SDKCONFIG_CONTENT}")
        file(WRITE "${CMAKE_SOURCE_DIR}/sdkconfig" "${EDGE_AGENT_SDKCONFIG_CONTENT}")
    endif()

    set(EDGE_AGENT_PARTITION_DEFAULTS "${CMAKE_BINARY_DIR}/edge_agent_partition_auto.defaults")
    file(WRITE "${EDGE_AGENT_PARTITION_DEFAULTS}"
        "# Auto-generated from flash size selection. Do not edit.\n"
        "CONFIG_PARTITION_TABLE_CUSTOM=y\n"
        "CONFIG_PARTITION_TABLE_CUSTOM_FILENAME=\"partitions_${EDGE_AGENT_FLASH_SIZE}.csv\"\n")

    list(APPEND EDGE_AGENT_SDKCONFIG_DEFAULTS "${EDGE_AGENT_PARTITION_DEFAULTS}")

    message(STATUS "${EDGE_AGENT_PROJECT_LOG_PREFIX} Partition table auto-selected: partitions_${EDGE_AGENT_FLASH_SIZE}.csv")
endif()

set(SDKCONFIG_DEFAULTS "${EDGE_AGENT_SDKCONFIG_DEFAULTS}")
